Shipment, Delivery and Req Order Tables and ETLs
LabKey/nircEHRModules pull request #91
Opened 2022-01-21 03:50 UTC by labkey-martyp

#### Rationale
Shipment, Delivery and Req Order related tables and ETLs

#### Changes
- LotNumber table and ETL and Fk to Demographics
- AnimalDelivery and AnimalDeliveryEsig tables and ETLs
- AnimalReqOrder and AnimalReqOrderEsig tables and ETLs
- AnimalShipment, AnimalVendor and ShipTo table and ETLs
- Delivery_State, Esig_Events, Req_Order_State, Req_Order_Type and Vendor_Approval_Code lookup sets and TSVs.

2022-01-21 16:02 UTC, ankurjuneja approved these changes

2022-01-21 16:03 UTC, ankurjuneja requested changes
looks like schema xml is missing

2022-01-21 20:31 UTC, labkey-martyp commented
> looks like schema xml is missing

Gah, I keep forgetting that.  Ok added now.  Thanks @ankurjuneja .

2022-01-22 16:45 UTC, labkey-jeckels approved these changes

2022-01-22 16:45 UTC, ankurjuneja approved these changes

2022-01-22 16:48 UTC, merged